name: Get Last Night's Stats
on: 
  schedule:
    - cron: 10 8 * 1,2,3,4,5,6,10,11,12 *

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.11.11
      - run: pip install -r requirements.txt
      - name: Get last night's stats
        env:
          SERVICE_BLOB: ${{ secrets.SERVICE_BLOB }}
        run: python3 analysis/get_last_night_stats.py 
      - name: Get optimal Six Picks lineup for last night
        env:
          SERVICE_BLOB: ${{ secrets.SERVICE_BLOB }}
        run: python3 analysis/six_picks.py 

